// Code generated by "stringer -type=register"; DO NOT EDIT.

package plc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[fieldIoConnection-0]
	_ = x[redSpeaker-1]
	_ = x[blueSpeaker-2]
	_ = x[redAmp-3]
	_ = x[blueAmp-4]
	_ = x[miscounts-5]
	_ = x[matchState-6]
	_ = x[registerCount-7]
}

const _register_name = "fieldIoConnectionredSpeakerblueSpeakerredAmpblueAmpmiscountsmatchStateregisterCount"

var _register_index = [...]uint8{0, 17, 27, 38, 44, 51, 60, 70, 83}

func (i register) String() string {
	if i < 0 || i >= register(len(_register_index)-1) {
		return "register(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _register_name[_register_index[i]:_register_index[i+1]]
}
